spring.application.name=spring-la-mia-pizzeria-crud

#data source
!nome del database da cambiare in new Apps (?createDatabaseIfNotExist=true)
spring.datasource.url=jdbc:mysql://localhost:3306/pizzeria
spring.datasource.username=root
spring.datasource.password=password


## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect

# Hibernate dal auto(create=(butta giù il DB e lo ricrea), create-drop=(crea e droppa dopo la chiusura dell'applicazione), validate(verifica solo loschema esistente nn modifica), update(esamina e aggiorna lo schema esistente), none(disabilita ogni manipolazione))
spring.jpa.hibernate.ddl-auto = update

# Data Formatting
spring.mvc.format.date=yyyy-MM-dd
spring.mvc.format.date-time=yyyy-MM-dd HH:mm:ss
spring.mvc.format.time=HH:mm:ss

#Impostazioni aggiuntive, utili per il testing(rimuoviamole poi)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
